---
- name: "Build EMVConnect SDK for iOS"
  hosts: localhost
  # hosts:
  connection: local
  gather_facts: no
  vars:
    folder: "../../"

  tasks:


    # - name: check that i have log file for all hosts on my local machine
    #   stat: path=/var/log/hosts/{{inventory_hostname}}.log
    #   delegate_to: localhost

    - name: Get SDK Version
      shell: "grep -m 1 'MARKETING_VERSION' {{ folder }}EMVConnectiOS.xcodeproj/project.pbxproj | cut -c 25- | sed 's/;$//'"
      register: sdk_version

    - name: Check File Exist
      aws_s3:
        src: "deploy.yml"
        bucket: "teste-release-demo-ios"
        object: "/EMVConnect/iOS/{{ sdk_version.stdout }}/EMVConnectiOS.zip"
        # mode: put
        mode: list
        overwrite: never
      register: stat_result

    - name: If File Exist Stop Playbook
      fail: msg="File exist on S3 Bucket"
      #when: stat_result.changed == false
      when: stat_result.changed == true

    - name: Build SDK
        - local_action: script create_fat_binaries_fw.sh
      # shell: |
      # sh create_fat_binaries_fw.sh
      

    # - name: Copy License file
    #   shell: "cp license build/Release-universal/license"
    #   args:
    #     chdir: "{{ folder }}"

    # - name: Create Zip file
    #   # shell: "zip -r EMVConnectiOS.zip license EMVConnectiOS.framework EMVConnectiOS.framework.dSYM"
    #   shell: "zip -r EMVConnectiOS.zip /EMVConnectiOS.xcframework"
    #   args:
    #     # chdir: "{{ folder }}/build/Release-universal"
    #     chdir: "{{ folder }}"

    # - name: Create Zip file
    #   archive:
    #     path: /EMVConnectiOS.xcframework
    #     dest: /release/EMVConnectiOS.zip
    #     format: zip

    # - name: Upload Zip to AWS S3
    #   shell: "aws s3 cp EMVConnectiOS.xcframework.zip s3://teste-release-demo-ios/EMVConnect/iOS/{{ sdk_version.stdout }}/ --grants read=uri=http://acs.amazonaws.com/groups/global/AllUsers"
    #   args:
    #     chdir: "{{ folder }}/release"

    # - name: Upload Tar GZ to AWS S3
    #   shell: "aws s3 cp EMVConnectiOS.tar.gz s3://zoop-release-sdk-ios-prd/EMVConnect/iOS/{{ sdk_version.stdout }}/ --grants read=uri=http://acs.amazonaws.com/groups/global/AllUsers"
    #   args:
    #     chdir: "{{ folder }}"

    # - name: Set PodSpec Version
    #   shell: "sed -ie 's/VERSION/{{ sdk_version.stdout }}/g' EMVConnectiOS.podspec"
    #   args:
    #     chdir: "{{ folder }}"

    # - name: Pod Spec Lint
    #   shell: "pod spec lint"
    #   args:
    #     chdir: "{{ folder }}"

    # - name: Publish Pod on CocoaPods
    #   shell: "pod trunk push EMVConnectiOS.podspec"
    #   args:
    #     chdir: "{{ folder }}"
